### ISSUE TITLE
can't use it on mac ver10.2.6 or lower

### ISSUE THREAD

**Issue by yangchris4** [zhihaozhang/thunder-Bypass#1]
<img width="431" alt="2018-06-01 8 19 37" src="https://user-images.githubusercontent.com/13220804/40840492-833415c8-65d9-11e8-8188-1072a8345d2c.png">
可以做个低版本也能用的吗？  感谢！

**Comment by zhihaozhang** [comment]
谢谢提醒，已经支持到了10.10
